wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713956674.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 4
      - 23
      - 42
      4: 3.11.9
      5: 0.16.6
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
